version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
      tag: '10'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run prettier -- --check .
            - run: npm run _install
            - run: npm run bootstrap
            - run: npm test
            - run: npm run build
workflows:
  build-and-test:
    jobs:
      - build-and-test
